package vu.lt.mybatis.model;

public class ReservationRoom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION_ROOM.RESERVEDROOMS_ID
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    private Integer reservedroomsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION_ROOM.RESERVATIONS_ID
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    private Integer reservationsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION_ROOM.RESERVEDROOMS_ID
     *
     * @return the value of PUBLIC.RESERVATION_ROOM.RESERVEDROOMS_ID
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    public Integer getReservedroomsId() {
        return reservedroomsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION_ROOM.RESERVEDROOMS_ID
     *
     * @param reservedroomsId the value for PUBLIC.RESERVATION_ROOM.RESERVEDROOMS_ID
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    public void setReservedroomsId(Integer reservedroomsId) {
        this.reservedroomsId = reservedroomsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION_ROOM.RESERVATIONS_ID
     *
     * @return the value of PUBLIC.RESERVATION_ROOM.RESERVATIONS_ID
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    public Integer getReservationsId() {
        return reservationsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION_ROOM.RESERVATIONS_ID
     *
     * @param reservationsId the value for PUBLIC.RESERVATION_ROOM.RESERVATIONS_ID
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    public void setReservationsId(Integer reservationsId) {
        this.reservationsId = reservationsId;
    }
}