package vu.lt.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import vu.lt.mybatis.model.ReservationRoom;

@Mapper
public interface ReservationRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION_ROOM
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    int deleteByPrimaryKey(@Param("reservedroomsId") Integer reservedroomsId, @Param("reservationsId") Integer reservationsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION_ROOM
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    int insert(ReservationRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION_ROOM
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    List<ReservationRoom> selectAll();
}