package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Reservation;

@Mapper
public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    Reservation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    List<Reservation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Wed Apr 24 00:33:13 EEST 2019
     */
    int updateByPrimaryKey(Reservation record);
}